using System.Numerics;
using System.Runtime.InteropServices;
using Agapanthe.Core;
using Agapanthe.Graphics;
using Agapanthe.Graphics.Memory;
using Agapanthe.Platform;
using Agapanthe.Rendering;
using Silk.NET.Input;

// M3 validation app: renders the spinning cube from M2, now TEXTURED with a procedurally
// generated sRGB checkerboard sampled through a full mip chain. Exercises the whole M3 memory
// path end-to-end on the GPU:
//   - vertex + index buffers live in DEVICE-LOCAL memory, filled once via the staging uploader
//     (GpuUploader) instead of Write<T> (which is host-visible only);
//   - a 256×256 RGBA8 checkerboard is uploaded to a device-local GpuImage, whose full mip chain
//     is generated by linear blits inside the same upload command buffer;
//   - a persistent per-material descriptor set (set 1, binding 0 = combined image sampler) points
//     at that texture and is bound every frame.
// The camera UBO on set 0 stays host-visible (per-frame Write<T>, correct). On exit the allocator
// prints its memory stats (device.Dispose, #if DEBUG) and the ResourceTracker prints its leak report.

var shaderDir = Path.Combine(AppContext.BaseDirectory, "shaders");

// Auto-close after N rendered frames when AGAPANTHE_MAX_FRAMES is set (CI/headless validation).
var maxFrames = int.TryParse(Environment.GetEnvironmentVariable("AGAPANTHE_MAX_FRAMES"), out var mf) ? mf : -1;
var renderedFrames = 0;

using var window = new EngineWindow("Agapanthe — M3 Textured Cube", 1280, 720);

GraphicsDevice? device = null;
Swapchain? swapchain = null;
ShaderCompiler? shaderCompiler = null;
ShaderModule? vertexShader = null;
ShaderModule? fragmentShader = null;
DescriptorSetLayout? frameSetLayout = null;
DescriptorSetLayout? materialSetLayout = null;
DescriptorAllocator? materialAllocator = null;
GraphicsPipeline? pipeline = null;
FrameRenderer? renderer = null;
GpuBuffer? vertexBuffer = null;
GpuBuffer? indexBuffer = null;
GpuImage? texture = null;
Sampler? sampler = null;
var cameraUbos = new GpuBuffer?[GraphicsDevice.FramesInFlight];

// Persistent set 1 (per-material). Struct handle, assigned once at load, bound every frame.
DescriptorSetHandle materialSet = default;

var camera = new Camera { Position = new Vector3(0f, 1.2f, 3f), Pitch = -0.3f };
var controller = new FreeCameraController();
var modelAngle = 0f;
uint indexCount = 0;
var resizePending = false;

// Hoisted out of the render handler so the delegate is allocated once, not per frame
// (spec §3.2.5, zero managed allocation on the hot path).
Action<CommandList, FrameContext>? recordCube = null;

window.Loaded += () =>
{
    var requiredExtensions = window.GetRequiredVulkanExtensions();
    device = new GraphicsDevice("Agapanthe Sandbox", requiredExtensions, window.VkSurface!);

    var (width, height) = window.FramebufferSize;
    swapchain = new Swapchain(device, width, height);
    camera.AspectRatio = (float)width / height;

    shaderCompiler = new ShaderCompiler();
    var vertSpirv = shaderCompiler.CompileFile(Path.Combine(shaderDir, "cube.vert"), ShaderStage.Vertex);
    var fragSpirv = shaderCompiler.CompileFile(Path.Combine(shaderDir, "cube.frag"), ShaderStage.Fragment);
    vertexShader = new ShaderModule(device, vertSpirv, ShaderStage.Vertex);
    fragmentShader = new ShaderModule(device, fragSpirv, ShaderStage.Fragment);

    // Geometry now lives in device-local memory: create the buffers as DeviceLocal (they gain
    // TRANSFER_DST automatically) and fill them through the staging uploader — Write<T> throws on
    // device-local memory by design (spec §3.2, architect decision session 2: uploads are explicit).
    var (vertices, indices) = Primitives.Cube();
    indexCount = (uint)indices.Length;
    vertexBuffer = new GpuBuffer(
        device, (ulong)(vertices.Length * Marshal.SizeOf<Vertex>()), BufferUsage.Vertex, MemoryDomain.DeviceLocal);
    indexBuffer = new GpuBuffer(
        device, (ulong)(indices.Length * sizeof(ushort)), BufferUsage.Index, MemoryDomain.DeviceLocal);

    // Procedural sRGB checkerboard (board decision: file decode belongs to M4 Assets; the GPU path
    // — staging → device-local → mips → sampler — is identical and fully exercised here). Two
    // contrasting *colored* cells (not pure black/white) so the sRGB encoding and the per-face color
    // modulation are both visible. Tightly packed RGBA8, one byte per channel.
    const uint texSize = 256;
    const uint checkerPx = 32;
    var pixels = new byte[texSize * texSize * 4];
    ReadOnlySpan<byte> cellA = [235, 179, 82, 255];  // warm amber
    ReadOnlySpan<byte> cellB = [46, 94, 138, 255];   // deep teal
    for (var y = 0u; y < texSize; y++)
    {
        for (var x = 0u; x < texSize; x++)
        {
            var color = ((x / checkerPx + y / checkerPx) & 1) == 0 ? cellA : cellB;
            var i = (int)((y * texSize + x) * 4);
            pixels[i + 0] = color[0];
            pixels[i + 1] = color[1];
            pixels[i + 2] = color[2];
            pixels[i + 3] = color[3];
        }
    }

    // Sampled texture with a full mip chain. TransferDst = staging copy target (mip 0);
    // TransferSrc = blit source for mip generation (M3-07). Upload transitions all levels to
    // ShaderReadOnlyOptimal, so it is ready to sample on the very first frame.
    texture = new GpuImage(
        device, texSize, texSize, PixelFormat.Rgba8Srgb,
        ImageUsage.Sampled | ImageUsage.TransferDst | ImageUsage.TransferSrc,
        GpuImage.FullMipChain(texSize, texSize));

    // One uploader for all load-time transfers, disposed immediately once the (synchronous) uploads
    // return — each upload already waited on its fence, so nothing it submitted is in flight and its
    // command pool + fence can be released right away. Nothing needs it past load.
    using (var uploader = new GpuUploader(device))
    {
        uploader.Upload<Vertex>(vertexBuffer, vertices);
        uploader.Upload<ushort>(indexBuffer, indices);
        uploader.Upload<byte>(texture, pixels);
    }

    // Default sampler: Linear min/mag, Linear mipmap, Repeat addressing (SamplerDesc zero-defaults).
    sampler = new Sampler(device);

    for (var i = 0; i < cameraUbos.Length; i++)
    {
        // Camera UBO stays host-visible: it is rewritten every frame, so Write<T> is correct here.
        cameraUbos[i] = new GpuBuffer(device, (ulong)Marshal.SizeOf<CameraUniforms>(), BufferUsage.Uniform);
    }

    frameSetLayout = new DescriptorSetLayout(
        device,
        [new DescriptorBinding(Binding: 0, DescriptorKind.UniformBuffer, ShaderStages.Vertex)]);

    // Set 1 = per-material (spec §3.4). One persistent combined-image-sampler, allocated from a
    // pool that is never reset per frame and written exactly once at load.
    materialSetLayout = new DescriptorSetLayout(
        device,
        [new DescriptorBinding(Binding: 0, DescriptorKind.CombinedImageSampler, ShaderStages.Fragment)]);
    materialAllocator = new DescriptorAllocator(device);
    materialSet = materialAllocator.AllocateSet(materialSetLayout);
    materialAllocator.WriteCombinedImageSampler(materialSet, 0, texture, sampler);

    // Declare only the attributes the shaders consume: position (0), color (1) and uv (3). Normal
    // (location 2) stays in the 44-byte stride but is unconsumed until M5 (lighting) — declaring an
    // attribute the shader does not read is a validation warning (spec §4).
    var cubeVertexLayout = new VertexLayout(
        Vertex.Layout.Stride,
        [Vertex.Layout.Attributes[0], Vertex.Layout.Attributes[1], Vertex.Layout.Attributes[3]]);

    pipeline = new GraphicsPipeline(device, new GraphicsPipelineDesc
    {
        VertexShader = vertexShader,
        FragmentShader = fragmentShader,
        VertexLayout = cubeVertexLayout,
        SetLayouts = [frameSetLayout, materialSetLayout],
        PushConstants = [new PushConstantRange(Offset: 0, Size: 64, ShaderStages.Vertex)],
        ColorFormat = swapchain.ColorFormat,
        DepthFormat = FrameRenderer.DepthFormat,
        DepthTest = true,
        // The Y-flipped Vulkan projection (MathHelpers.PerspectiveVulkan) mirrors winding in
        // framebuffer space, so the cube's CCW-from-outside faces arrive clockwise.
        FrontFace = FrontFace.Clockwise,
    });

    renderer = new FrameRenderer(device, swapchain, () => window.FramebufferSize)
    {
        ClearColor = (0.02f, 0.02f, 0.05f, 1f),
    };

    recordCube = (cmd, frame) =>
    {
        var ubo = cameraUbos[frame.Slot]!;
        var uniforms = new CameraUniforms(camera.ViewMatrix, camera.ProjectionMatrix);
        ubo.Write<CameraUniforms>(new ReadOnlySpan<CameraUniforms>(in uniforms));

        var set = frame.AllocateSet(frameSetLayout!);
        frame.WriteUniformBuffer(set, 0, ubo);

        cmd.BindPipeline(pipeline!);
        cmd.BindDescriptorSet(pipeline!, 0, set);           // set 0: per-frame camera UBO
        cmd.BindDescriptorSet(pipeline!, 1, materialSet);   // set 1: persistent per-material texture
        cmd.BindVertexBuffer(vertexBuffer!);
        cmd.BindIndexBuffer(indexBuffer!, IndexFormat.UInt16);

        var model = Matrix4x4.CreateRotationY(modelAngle);
        cmd.PushConstants(pipeline!, ShaderStages.Vertex, in model);
        cmd.DrawIndexed(indexCount);
    };

    Log.Info($"Sandbox: initialized on '{device.AdapterName}'. Rendering textured cube — clic pour capturer la souris, WASD + souris, Échap libère puis quitte.");
};

// MoltenVK does not always report OUT_OF_DATE on resize; recreate explicitly to be safe.
window.FramebufferResized += (w, h) =>
{
    resizePending = true;
    if (w > 0 && h > 0)
    {
        camera.AspectRatio = (float)w / h;
    }
};

// Escape is two-stage: the first press releases the mouse capture, quitting only happens
// when the cursor is already free. Edge-triggered so holding the key can't skip a stage.
window.KeyPressed += key =>
{
    if (key != Key.Escape)
    {
        return;
    }

    if (window.MouseCaptured)
    {
        window.SetMouseCaptured(false);
    }
    else
    {
        window.Close();
    }
};

window.Updated += dt =>
{
    modelAngle += (float)dt * 0.8f;

    // Camera control only while the cursor is captured (a click in the window captures it,
    // focus loss releases it) — mouse motion outside the window never steers the view.
    if (!window.MouseCaptured)
    {
        return;
    }

    var input = new CameraInput(
        moveForward: window.IsKeyDown(Key.W),
        moveBackward: window.IsKeyDown(Key.S),
        moveLeft: window.IsKeyDown(Key.A),
        moveRight: window.IsKeyDown(Key.D),
        moveUp: window.IsKeyDown(Key.Space),
        moveDown: window.IsKeyDown(Key.ControlLeft),
        lookDelta: window.MouseDelta);
    controller.Update(camera, (float)dt, in input);
};

window.Rendered += _ =>
{
    if (renderer is null || swapchain is null)
    {
        return;
    }

    if (resizePending)
    {
        resizePending = false;
        renderer.RequestResize();
    }

    renderer.DrawFrame(recordCube!);

    if (maxFrames > 0 && ++renderedFrames >= maxFrames)
    {
        window.Close();
    }
};

try
{
    window.Run();
}
finally
{
    // Tear down in reverse creation order, GPU-idle first — runs even if init threw
    // inside the Loaded handler, so the leak report is always produced.
    renderer?.WaitIdle();
    renderer?.Dispose();
    pipeline?.Dispose();
    // The persistent per-material set dies with its allocator; its pools are destroyed
    // synchronously, which is why the GPU must already be idle (renderer.WaitIdle above).
    materialAllocator?.Dispose();
    materialSetLayout?.Dispose();
    frameSetLayout?.Dispose();
    foreach (var ubo in cameraUbos)
    {
        ubo?.Dispose();
    }

    indexBuffer?.Dispose();
    vertexBuffer?.Dispose();
    // Sampler and texture disposal is deferred through the DeletionQueue (non-capturing payload);
    // the FlushAll below drains it while the device is still alive and idle.
    sampler?.Dispose();
    texture?.Dispose();
    fragmentShader?.Dispose();
    vertexShader?.Dispose();
    shaderCompiler?.Dispose();
    // GpuBuffer/GpuImage/Sampler disposal is deferred through the DeletionQueue; drain it while the
    // device still exists (the device is idle at this point).
    device?.DeletionQueue.FlushAll();
    swapchain?.Dispose();
    device?.Dispose();
    window.Dispose();
}

var clean = ResourceTracker.Report();
Log.Info(clean ? "Sandbox: clean shutdown, no GPU resource leaks." : "Sandbox: LEAKS DETECTED (see above).");
Environment.Exit(clean ? 0 : 1);

/// <summary>Set 0, binding 0 — must match shaders/cube.vert layout (two mat4, 128 bytes).</summary>
[StructLayout(LayoutKind.Sequential)]
internal readonly struct CameraUniforms(Matrix4x4 view, Matrix4x4 proj)
{
    public readonly Matrix4x4 View = view;
    public readonly Matrix4x4 Proj = proj;
}
