using System.Numerics;
using Agapanthe.Assets.Model;
using Agapanthe.Graphics;

namespace Agapanthe.Rendering;

/// <summary>
/// Turns a CPU-side <see cref="ModelAsset"/> into a GPU-resident <see cref="Scene"/>. All load-time
/// transfers — the 1×1 placeholders, every texture, and every mesh's vertex/index buffers — go through a
/// <b>single</b> <see cref="GpuUploader"/> opened in one <c>using</c> (architect decision session 3, #6),
/// so the transient command pool/fence are created and torn down exactly once for the whole load.
/// <para>
/// The Renderer (M4-10) supplies the persistent <see cref="DescriptorAllocator"/> and the set-1
/// <see cref="DescriptorSetLayout"/> (<see cref="MaterialLayout"/>); both outlive the scene and are not
/// owned by it. Everything the build allocates is owned by the returned <see cref="Scene"/>. On any failure
/// mid-build, resources created so far are disposed before rethrowing.
/// </para>
/// </summary>
public static class SceneBuilder
{
    /// <summary>
    /// Builds a scene from <paramref name="model"/>. Textures decode-format is chosen by the image's
    /// <see cref="ImageAsset.IsSrgb"/> flag (sRGB base color/emissive vs linear normal/MR/AO), with a full
    /// mip chain generated by blits. Meshes with <see cref="MeshAsset.MaterialIndex"/> <c>-1</c> (or an
    /// out-of-range index) share a single engine-default material (glTF factor defaults + placeholders).
    /// </summary>
    public static Scene Build(
        GraphicsDevice device,
        ModelAsset model,
        DescriptorAllocator materialAllocator,
        DescriptorSetLayout materialSetLayout)
    {
        ArgumentNullException.ThrowIfNull(device);
        ArgumentNullException.ThrowIfNull(model);
        ArgumentNullException.ThrowIfNull(materialAllocator);
        ArgumentNullException.ThrowIfNull(materialSetLayout);

        var samplerCache = new SamplerCache(device);
        var placeholders = Array.Empty<GpuImage>();
        var textures = Array.Empty<GpuImage>();
        var meshes = Array.Empty<Mesh>();
        var materials = Array.Empty<Material>();

        try
        {
            // One uploader for the entire load: placeholders, textures, then geometry. Disposed at the end
            // of this block — every upload is synchronous (waits on its fence), so nothing is in flight.
            using (var uploader = new GpuUploader(device))
            {
                // Pre-allocated and filled in place so a failure on the 2nd/3rd placeholder still
                // leaves the earlier ones reachable by the catch below (audit M4, finding M2) —
                // same pattern as the texture and mesh loops.
                placeholders = new GpuImage[3];
                FillPlaceholders(device, uploader, placeholders);
                var slots = new Placeholders(placeholders[0], placeholders[1], placeholders[2]);

                textures = new GpuImage[model.Images.Count];
                for (var i = 0; i < textures.Length; i++)
                {
                    textures[i] = UploadTexture(device, uploader, model.Images[i]);
                }

                meshes = new Mesh[model.Meshes.Count];
                for (var i = 0; i < meshes.Length; i++)
                {
                    meshes[i] = Mesh.Create(device, uploader, model.Meshes[i]);
                }

                materials = BuildMaterials(
                    device, model, materialAllocator, materialSetLayout, samplerCache, textures, in slots,
                    out var defaultMaterialIndex);

                var instances = BuildInstances(model, meshes, materials, defaultMaterialIndex);

                // World-space AABB folded from the CPU-side mesh positions (before upload frees nothing —
                // the DTO arrays are still live). Consumed by the Renderer/Sandbox for camera framing and
                // the shadow ortho fit, so it is computed once here rather than re-walking vertices per use.
                var (boundsMin, boundsMax) = ComputeWorldBounds(model.Meshes);

                return new Scene(
                    instances, meshes, materials, textures, placeholders, samplerCache, model.Name,
                    boundsMin, boundsMax);
            }
        }
        catch
        {
            DisposeAll(materials);
            DisposeAll(meshes);
            DisposeAll(textures);
            DisposeAll(placeholders);
            samplerCache.Dispose();
            throw;
        }
    }

    /// <summary>
    /// Folds a world-space axis-aligned bounding box over every mesh's positions, each transformed by its
    /// <see cref="MeshAsset.WorldTransform"/>. Pure and GPU-free so it is unit-testable on synthetic meshes.
    /// A model with no geometry (no meshes, or meshes with no positions) returns the degenerate box
    /// <c>(0,0,0)–(0,0,0)</c> rather than the inverted infinities of an empty fold.
    /// </summary>
    public static (Vector3 Min, Vector3 Max) ComputeWorldBounds(IReadOnlyList<MeshAsset> meshes)
    {
        ArgumentNullException.ThrowIfNull(meshes);

        var min = new Vector3(float.PositiveInfinity);
        var max = new Vector3(float.NegativeInfinity);

        foreach (var mesh in meshes)
        {
            var world = mesh.WorldTransform;
            foreach (var localPos in mesh.Positions)
            {
                var p = Vector3.Transform(localPos, world);
                min = Vector3.Min(min, p);
                max = Vector3.Max(max, p);
            }
        }

        // min.X > max.X only when the fold never ran (no vertices): collapse to a point at the origin.
        return min.X > max.X ? (Vector3.Zero, Vector3.Zero) : (min, max);
    }

    /// <summary>
    /// The three shared 1×1 placeholders bound to absent texture slots (index order matches the array
    /// filled by <see cref="FillPlaceholders"/>): white sRGB (base color/emissive absent), neutral
    /// normal <c>(128,128,255)</c> linear (normal absent), and white linear (MR/AO absent).
    /// </summary>
    private readonly record struct Placeholders(GpuImage WhiteSrgb, GpuImage NormalNeutral, GpuImage LinearWhite);

    private static void FillPlaceholders(GraphicsDevice device, GpuUploader uploader, GpuImage[] placeholders)
    {
        // White sRGB: baseColor/emissive absent → factor passes through unchanged (emissive factor is 0 by
        // default, so absent emissive stays black regardless).
        placeholders[0] = CreatePixel(device, uploader, PixelFormat.Rgba8Srgb, 255, 255, 255, 255);
        // Neutral tangent-space normal (0,0,1) encoded → (128,128,255); linear data, so UNORM.
        placeholders[1] = CreatePixel(device, uploader, PixelFormat.Rgba8Unorm, 128, 128, 255, 255);
        // White linear: metallic-roughness and occlusion absent → the factor/1.0 dominates.
        placeholders[2] = CreatePixel(device, uploader, PixelFormat.Rgba8Unorm, 255, 255, 255, 255);
    }

    private static GpuImage CreatePixel(GraphicsDevice device, GpuUploader uploader, PixelFormat format, byte r, byte g, byte b, byte a)
    {
        // 1×1, single mip: no blit source needed, so no TransferSrc.
        var image = new GpuImage(device, 1, 1, format, ImageUsage.Sampled | ImageUsage.TransferDst, mipLevels: 1);
        try
        {
            Span<byte> texel = [r, g, b, a];
            uploader.Upload<byte>(image, texel);
            return image;
        }
        catch
        {
            image.Dispose();
            throw;
        }
    }

    private static GpuImage UploadTexture(GraphicsDevice device, GpuUploader uploader, ImageAsset image)
    {
        // sRGB vs linear is decided by the material slot (carried on the ImageAsset), not the file.
        var format = image.IsSrgb ? PixelFormat.Rgba8Srgb : PixelFormat.Rgba8Unorm;
        var width = (uint)image.Width;
        var height = (uint)image.Height;
        var mipLevels = GpuImage.FullMipChain(width, height);

        // Sampled = read in shader; TransferDst = staging copy target (mip 0); TransferSrc = blit source for
        // mip generation. The uploader transitions every level to ShaderReadOnlyOptimal.
        var gpuImage = new GpuImage(
            device, width, height, format,
            ImageUsage.Sampled | ImageUsage.TransferDst | ImageUsage.TransferSrc, mipLevels);
        try
        {
            uploader.Upload<byte>(gpuImage, image.Rgba8Pixels);
            return gpuImage;
        }
        catch
        {
            gpuImage.Dispose();
            throw;
        }
    }

    private static Material[] BuildMaterials(
        GraphicsDevice device,
        ModelAsset model,
        DescriptorAllocator allocator,
        DescriptorSetLayout layout,
        SamplerCache samplerCache,
        GpuImage[] textures,
        in Placeholders slots,
        out int defaultMaterialIndex)
    {
        // A default material is needed when some mesh has no (or an invalid) material index.
        var needsDefault = false;
        foreach (var mesh in model.Meshes)
        {
            if (mesh.MaterialIndex < 0 || mesh.MaterialIndex >= model.Materials.Count)
            {
                needsDefault = true;
                break;
            }
        }

        var count = model.Materials.Count + (needsDefault ? 1 : 0);
        var materials = new Material[count];
        for (var i = 0; i < model.Materials.Count; i++)
        {
            materials[i] = BuildMaterial(device, allocator, layout, samplerCache, textures, in slots, model.Materials[i]);
        }

        defaultMaterialIndex = -1;
        if (needsDefault)
        {
            defaultMaterialIndex = model.Materials.Count;
            // A blank MaterialAsset carries the glTF factor defaults and -1 image slots → placeholders.
            materials[defaultMaterialIndex] = BuildMaterial(
                device, allocator, layout, samplerCache, textures, in slots,
                new MaterialAsset { Name = "Default (engine)" });
        }

        return materials;
    }

    private static Material BuildMaterial(
        GraphicsDevice device,
        DescriptorAllocator allocator,
        DescriptorSetLayout layout,
        SamplerCache samplerCache,
        GpuImage[] textures,
        in Placeholders slots,
        MaterialAsset asset)
    {
        var sampler = samplerCache.Get(asset.TextureSettings);

        var baseColor = Resolve(asset.BaseColorImage, slots.WhiteSrgb, textures);
        var normal = Resolve(asset.NormalImage, slots.NormalNeutral, textures);
        var metallicRoughness = Resolve(asset.MetallicRoughnessImage, slots.LinearWhite, textures);
        var occlusion = Resolve(asset.OcclusionImage, slots.LinearWhite, textures);
        var emissive = Resolve(asset.EmissiveImage, slots.WhiteSrgb, textures);

        // Packing must match MaterialUniforms / the M4-M5 fragment shader:
        // mrno = (metallic, roughness, normalScale, occlusionStrength).
        var uniforms = new MaterialUniforms(
            asset.BaseColorFactor,
            new Vector4(asset.MetallicFactor, asset.RoughnessFactor, asset.NormalScale, asset.OcclusionStrength),
            new Vector4(asset.EmissiveFactor, asset.EmissiveStrength),
            new Vector4(asset.AlphaCutoff, (float)(int)asset.AlphaMode, 0f, 0f));

        return new Material(
            device, allocator, layout, in uniforms, asset.AlphaMode, asset.Name,
            baseColor, normal, metallicRoughness, occlusion, emissive, sampler);
    }

    private static GpuImage Resolve(int index, GpuImage placeholder, GpuImage[] textures)
        => index >= 0 && index < textures.Length ? textures[index] : placeholder;

    private static MeshInstance[] BuildInstances(ModelAsset model, Mesh[] meshes, Material[] materials, int defaultMaterialIndex)
    {
        var instances = new MeshInstance[meshes.Length];
        for (var i = 0; i < meshes.Length; i++)
        {
            var materialIndex = model.Meshes[i].MaterialIndex;
            var material = materialIndex >= 0 && materialIndex < model.Materials.Count
                ? materials[materialIndex]
                : materials[defaultMaterialIndex];
            instances[i] = new MeshInstance(meshes[i], material);
        }

        return instances;
    }

    private static void DisposeAll(Material[] materials)
    {
        foreach (var material in materials)
        {
            material?.Dispose();
        }
    }

    private static void DisposeAll(Mesh[] meshes)
    {
        foreach (var mesh in meshes)
        {
            mesh?.Dispose();
        }
    }

    private static void DisposeAll(GpuImage[] images)
    {
        foreach (var image in images)
        {
            image?.Dispose();
        }
    }
}
